name: SkulMS CI  
on:
   push: 
      branches: [staging] 
 
jobs:

   login:
     runs-on: ubuntu-latest
     steps:
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
        
   cd: 
     runs-on: ubuntu-latest 
     
     steps: 
       - uses: actions/checkout@v2
       - name: Build 
         run: docker build -t skulms . 
       - name: Tags 
         run: | 
           docker tag skulms ${{ secrets.DOCKER_USERNAME }}/skulms:staging 
       - name: Push 
         run: | 
           docker push ${{ secrets.DOCKER_USERNAME }}/skulms:staging
